# Generated by Django 5.1.1 on 2024-09-08 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video480p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file_480p', models.FileField(blank=True, null=True, upload_to='videos')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_480p', to='content.video')),
            ],
        ),
        migrations.CreateModel(
            name='Video720p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file_720p', models.FileField(blank=True, null=True, upload_to='videos')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_720p', to='content.video')),
            ],
        ),
    ]
