# Generated by Django 5.1.1 on 2024-09-17 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video1080p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file_1080p', models.FileField(blank=True, null=True, upload_to='videos')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_1080p', to='content.video')),
            ],
        ),
    ]
