# Generated by Django 5.1.1 on 2024-09-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_video1080p'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='group',
            field=models.CharField(choices=[('new', 'New on Videoflix'), ('documentary', 'Documentary'), ('drama', 'Drama'), ('romance', 'Romance')], default='new', max_length=20),
        ),
    ]
