# Generated by Django 5.1.1 on 2024-09-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_video_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='group',
            field=models.CharField(choices=[('documentary', 'Documentary'), ('drama', 'Drama'), ('romance', 'Romance')], default='documentary', max_length=20),
        ),
    ]
