# Generated by Django 5.1.1 on 2024-09-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_video_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='new_on_videoflix',
            field=models.BooleanField(default=True),
        ),
    ]
