# Generated by Django 5.1.1 on 2024-09-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_video_new_on_videoflix'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails'),
        ),
    ]
